import { Router } from "express";
import { prisma } from "../../lib/prisma";
import { validate } from "../../middleware/validate";
import { setCylinderPriceSchema } from "./cylinderPricesSchema";

export const cylinderPricesRouter = Router();

// POST /cylinder-prices - sets the price for a brand+size. Deliberately
// an upsert, not a plain create: prices change over time, and re-setting
// the price for an existing brand+size should update that row, not fail
// with a duplicate-key error just because one already exists.
cylinderPricesRouter.post("/", validate(setCylinderPriceSchema), async (req, res) => {
    const { brand, size, price } = req.body;

    const cylinderPrice = await prisma.cylinderPrice.upsert({
        // "brand_size" is prisma's autogenerated name for the compound
        // unique constraint we declared as @@unique([brand, size]) - it
        // joins the field names in declared order
        where: { brand_size: { brand, size } },
        update: { price }, // runs if this brand+size already has a price
        create: { brand, size, price }, // runs the first time
    });

    // 200, not 201: this call might just as easily update a new resource
    // not only create it
    res.status(200).json(cylinderPrice);
});